FROM python:3.9-slim

WORKDIR /app

COPY reviews_service.py /app/
COPY requirements-reviews.txt /app/

RUN pip install --no-cache-dir -r requirements-reviews.txt

EXPOSE 5000

CMD ["python", "reviews_service.py"]