
version: '3.9'

services:
  user_analysis:
    build:
      context: ./microservices/user_analysis
    container_name: user_analysis_service
    ports:
      - "5001:5000"
    restart: unless-stopped

  feedback_analysis:
    build:
      context: ./microservices/feedback_analysis
    container_name: feedback_analysis_service
    ports:
      - "5002:5000"
    restart: unless-stopped

  behavior_analysis:
    build:
      context: ./microservices/behavior_analysis
    container_name: behavior_analysis_service
    ports:
      - "5003:5000"
    restart: unless-stopped

  streamlit:
    build:
      context: ./streamlit_app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - user_analysis
      - feedback_analysis
      - behavior_analysis
    restart: unless-stopped
